# Generated by Django 3.2.8 on 2021-10-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('episodes', models.IntegerField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('popularity', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Anime',
            },
        ),
    ]
